### ISSUE TITLE
Unable to login with GitHub or Google

### ISSUE THREAD

**Issue by kabilar** [sensein/brainkb-ui#5]
When logging into https://beta.brainkb.org/, I receive the following errors:

- GitHub login error
  <img src="https://github.com/user-attachments/assets/0de68c21-cd09-4fc5-bd23-cc8499957ae7" height="200">
- Google login error
  <img src="https://github.com/user-attachments/assets/7eaba348-5bb4-463e-b78d-e4ea5e64bf27" height="200">

A few follow-up questions on the registration flow:
1. Do I need to be an authorized user to be able to log in?
2. How does this approval process happen?
3. In addition to the `Login` button, should we also have a `Sign up` button?

**Comment by tekrajchhetri** [comment]
@kabilar The reason why you're seeing this error is because I haven't enabled the production version of google auth. I had only used the test version for which you can specify the test email to allow the access.

**Comment by kabilar** [comment]
Thanks.  That makes sense.  What pages require logging in?  Can you please privately share with me the test credentials so that I can view those pages?

**Comment by tekrajchhetri** [comment]
Currently, there's nothing special. We're more focused on implementing model-based UI and the work got slow because we first need to finalize assertion-evidence ontology

**Comment by kabilar** [comment]
Thanks @tekrajchhetri.  Should I then hold off on reviewing the user interface - https://beta.brainkb.org?  Could you please point me to the assertion-evidence ontology so that I can review that piece?

**Comment by tekrajchhetri** [comment]
Little correction: we're not talking about the final version of ontology as ontology development is an iterative process and will evolve overtime. With the word "finalize" I was referring to the usable initial draft version of ontology. Perhaps, I should have used the word "draft" and not  "finalize".

**Comment by tekrajchhetri** [comment]
@kabilar I think this issue can be closed as it really is not an issue, it's just we need to setup with proper token. what do you think?

**Comment by tekrajchhetri** [comment]
Closing this issue as it's really not an issue, it's just that there's a need to configure.

**Comment by tekrajchhetri** [comment]
@kabilar GitHub configuration has been updated. So now everyone should be able to login.
